---
- name: Manage groups (Windows)
  ansible.builtin.include_tasks:
    file: noauto_groups_Windows.yml
  when: ansible_os_family == 'Windows'

- name: Manage groups (Unix)
  ansible.builtin.include_tasks:
    file: noauto_groups_Unix.yml
  when: ansible_os_family != 'Windows'
