---
- name: Manage users (Windows)
  ansible.builtin.include_tasks:
    file: noauto_users_Windows.yml
  when: ansible_os_family == 'Windows'

- name: Manage users (Unix)
  ansible.builtin.include_tasks:
    file: noauto_users_Unix.yml
  when: ansible_os_family != 'Windows'
