---
- name: Manage admin access (Windows)
  ansible.builtin.include_tasks:
    file: noauto_sudo_setup_Windows.yml
  loop: "{{ user_setup_users }}"
  loop_control:
    loop_var: user
  when:
    - ansible_os_family == 'Windows'
    - (user.sudo_access is defined and user.sudo_access) or (user.state | default('present') == 'absent')

- name: Manage sudo access (Unix)
  ansible.builtin.include_tasks:
    file: noauto_sudo_setup_Unix.yml
  loop: "{{ user_setup_users }}"
  loop_control:
    loop_var: user
  when:
    - ansible_os_family != 'Windows'
    - ((user.sudo_access is defined and user.sudo_access) and (ansible_facts.getent_passwd[user.name][1] | int != 0)) or (user.state | default('present') == 'absent')
