---
- name: Manage passwords (Windows)
  ansible.builtin.include_tasks:
    file: noauto_passwords_Windows.yml
  when: ansible_os_family == 'Windows'

- name: Manage passwords (Unix)
  ansible.builtin.include_tasks:
    file: noauto_passwords_Unix.yml
  when: ansible_os_family != 'Windows'
