---
- name: Manage user directories
  block:
    - name: Ensure user directories exist
      ansible.builtin.file:
        path: "{{ ansible_facts.getent_passwd[user.name][4] }}/{{ folder.name }}"
        state: directory
        mode: "755"
        owner: "{{ user.name }}"
        group: "{{ user.name }}"
      become: true
      loop: "{{ user.user_directories }}"
      loop_control:
        loop_var: folder

    - name: Ensure env vars are set for user directories
      ansible.builtin.lineinfile:
        path: "{{ ansible_facts.getent_passwd[user.name][4] }}/{{ user.env_var_file }}"
        line: 'export {{ folder.env_var }}="{{ ansible_facts.getent_passwd[user.name][4] }}/{{ folder.name }}"'
      become: true
      loop: "{{ user.user_directories }}"
      loop_control:
        loop_var: folder
