---
- name: Check if env var file exists
  ansible.builtin.stat:
    path: "{{ getent_passwd[user.name][4] }}/{{ user.env_var_file }}"
  register: user_setup_env_var_file
  become: true

- name: Ensure env var file exists
  ansible.builtin.file:
    path: "{{ getent_passwd[user.name][4] }}/{{ user.env_var_file }}"
    state: touch
    mode: "600"
    owner: "{{ user.name }}"
    group: "{{ user_setup_root_group if (getent_passwd[user.name][1] | int == 0) else user.name }}"
  become: true
  when: not user_setup_env_var_file.stat.exists
