---
- name: Set Windows user password if user exists
  ansible.windows.win_user:
    name: "{{ user.name }}"
    password: "{{ user.password }}"
  become: true
  become_method: ansible.builtin.runas
  become_user: SYSTEM
  loop: "{{ user_setup_users }}"
  loop_control:
    loop_var: user
  when:
    - user.password is defined
    - user.state | default('present') == 'present'
    - getent_passwd[user.name] is defined
  no_log: true
