---
- name: Fetch Unix user and group information
  ansible.builtin.getent:
    database: passwd

- name: Set Unix user password if user exists
  ansible.builtin.user:
    name: "{{ user.name }}"
    password: >-
      {{ user.password | password_hash('sha512', user.password_salt)
         if user.password_salt is defined
         else user.password | password_hash('sha512') }}
    create_home: "{{ user.create_home | default(true) }}"
    home: "{{ '/nonexistent' if not (user.create_home | default(true)) else omit }}"
  become: true
  loop: "{{ user_setup_users }}"
  loop_control:
    loop_var: user
  when:
    - user.password is defined
    - getent_passwd[user.name] is defined
  no_log: true
