---
- name: Ensure we are using apt
  ansible.builtin.fail:
    msg: "This role only supports {{ ansible_os_family }} systems that use apt as a package manager."
  when: ansible_pkg_mgr != "apt"

- name: Install user_setup dependencies via apt
  when: ansible_pkg_mgr == "apt"
  block:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      become: true

    - name: Ensure user_setup dependencies are installed
      ansible.builtin.apt:
        name: "{{ user_setup_dep_pkgs }}"
        state: present
      become: true
