---
- name: Converge
  hosts: all

  vars:
    ansible_user: root
    user_setup_password: "TempSec!Pass#"
    user_setup_password_salt: "dc0b318e9e5511e1"
    user_setup_groups:
      - name: test
        system: false
    user_setup_users:
      - name: "{{ ansible_user }}"
        shell: "/bin/bash"
        groups:
          - test
        groups_append: true
        password: "{{ user_setup_password | password_hash('sha512', user_setup_password_salt) }}"
        env_var_file: ".env_vars"
        user_directories:
          - name: ".local/share/archive"
            env_var: "XDG_ARCHIVE_DIR"
          - name: ".config"
            env_var: "XDG_CONFIG_DIR"
          - name: "desktop"
            env_var: "XDG_DESKTOP_DIR"
          - name: "documents"
            env_var: "XDG_DOCUMENTS_DIR"
          - name: "downloads"
            env_var: "XDG_DOWNLOAD_DIR"
          - name: "music"
            env_var: "XDG_MUSIC_DIR"
          - name: "pictures"
            env_var: "XDG_PICTURES_DIR"
          - name: "tools"
            env_var: "XDG_TOOLS_DIR"
          - name: "videos"
            env_var: "XDG_VIDEOS_DIR"
        ssh_setup: true
        ssh_directory: ".ssh"
        ssh_public_keys:
          - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBL3+59egObwwPuBKo1caTnovj6ZliOumpwMcpdL3NV7 user@hostname"

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      become: true
      when: ansible_os_family == 'Debian'

  roles:
    - role: pluggero.user_setup
