---
- name: Converge
  hosts: all

  vars_files:
    - ../../vars/molecule_vars.yml

  vars:
    ansible_user: root

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      become: true
      when: ansible_os_family == 'Debian'

  roles:
    - role: pluggero.user_setup
