---
- name: Converge
  gather_facts: true
  hosts: all

  vars_files:
    - ../../vars/molecule_vars_windows.yml

  vars:
    ansible_user: vagrant
    ansible_password: vagrant
    ansible_become_password: vagrant

  roles:
    - role: pluggero.user_setup
